console.log('Static test start');
import './first.js';
console.log('first.js loaded');
import 'dotenv/config';
console.log('dotenv loaded');
import express from "express";
console.log('express loaded');
import http from "http";
console.log('http loaded');
import mongoose from "mongoose";
console.log('mongoose loaded');
import cors from "cors";
console.log('cors loaded');
import helmet from "helmet";
console.log('helmet loaded');
import rateLimit from "express-rate-limit";
console.log('rateLimit loaded');
import mongoSanitize from "express-mongo-sanitize";
console.log('mongoSanitize loaded');
import cookieParser from "cookie-parser";
console.log('cookieParser loaded');
import compression from 'compression';
console.log('compression loaded');
import { logger } from "./utils/logger.js";
console.log('logger loaded');
import { cacheMiddleware } from "./utils/cache.js";
console.log('cache loaded');
import WebSocketManager from "./sockets/WebSocketManager.js";
console.log('WebSocketManager loaded');
import authRoutes from "./routes/auth.js";
console.log('authRoutes loaded');
import userRoutes from "./routes/userRoutes.js";
console.log('userRoutes loaded');
import chatRoutes from "./routes/chatRoutes.js";
console.log('chatRoutes loaded');

console.log('All static imports finished');
process.exit(0);
